### ISSUE TITLE
Errors :)

### ISSUE THREAD

**Issue by malutanpetronel** [frjo/ansible-roles#3]
Hi frjo
It looks that userdot.yml produce errors as that path does not exist.
However I removed userdot/ from the paths and it goes further more until another error:

changed: [...] => (item=testrules.v4)
failed: [...] (item=testrules.v6) => {"changed": false, "item": "testrules.v6", "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'interface'"}
	to retry, use: --limit @/home/../frjo/mail-server-playbook.retry

Did you run it and it works ?
Do this helps you or should I move on and create my own ansible :)

**Comment by malutanpetronel** [comment]
did you forgot to push testrules.v4 and v6 ? Can you provide an example of these files please ?

**Comment by malutanpetronel** [comment]
I did commented
- include: iptables-persistent.yml
  tags:
    - firewall

and it worked up to TASK [mailserver : run postmap on hash files] 
checking...

**Comment by malutanpetronel** [comment]
added a task to Set hostname... and go on again

**Comment by frjo** [comment]
The firewall errors comes from you not having an ipv6 interface, just now puched some code that checks this. All my servers use ipv6 so I had not encountered this issue.

Userdot files I have in a root files directory, have set   ignore_errors: yes for the tasks for now. Should write this up in the readme.

The last error seems to come from either mailrelay or mailserver roles. No idea what causing it.

All the roles here are in active use on multiple servers, and have been for years.

**Comment by frjo** [comment]
Happy that you find my roles useful! In the future please add one issue per problem.

**Comment by malutanpetronel** [comment]
Thank you Fredrik Jonsson.

I am in a process of learning Ansible and creating my own EMail server, in a flexible way, so that never happen again paying to much to providers like Hostmonster which catch clients with a low price than every year increase their needs :)

I found your work great and together with ispmail of Cristoph I did really learned more

**Comment by frjo** [comment]
I use the mailserver role for my own mail server and a couple of others. Read more here: <https://xdeb.org/post/2018/02/07/run-your-own-mail-server-with-postfix-and-dovecot/>
